# Generated by Django 6.0.5 on 2026-05-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_invite_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_3154fc_idx',
            old_name='chat_messag_convers_7d0bd9_idx',
        ),
    ]
